### ISSUE TITLE
感谢大佬

### ISSUE THREAD

**Issue by lanyangyang1234** [diyanqi/Lenovo-Xiaoxin-Air14-2019-IWL-Hackintosh-EFI#1]
感谢大佬的EFI，机型跟示例机型一样。想问问大佬几点问题：
1. WIFI和声卡问题：只有先启动PE，再启动hackintosh才能两者同时拥有，否则总有一个欠缺
2. 从hackintosh关机后，OC引导界面无法选择操作系统，键盘不可用，外接键盘可用
想了解一下大佬有遇到以上问题吗，是如何解决的呢，是否是因为BIOS有未设置的地方。

**Comment by diyanqi** [comment]
@lanyangyang1234 感谢您的使用。关于第一个问题，我的EFI刚配置好第1、2次启动时也会出现声卡、WiFi、包括蓝牙几选一的情况，但到后来开机次数多了，该问题自然而然就修复了。怀疑是kext驱动编译的问题，本人的经验是，系统使用时间越长就越稳定。我现在使用就没有这样的现象。

关于第二个问题，内置键盘确实有很大概率不可用，不论是在BIOS引导时按F12还是在OC界面选择系统。本人的解决方法是，如果要进行BIOS设置或选择启动盘，用针戳电脑右边的一个小孔，再接一个外置键盘，在OC引导的地方用CTRL+enter选择要进入的系统，这样下次再进入OC的时候就能默认启动macos了。猜想是这个机型不太稳定，因为即使我在使用Windows的时候也会有各种各样的BUG，非常难受。另外，BIOS就把安全启动关掉，没有额外的设置。

**Comment by lanyangyang1234** [comment]
好的，感谢您的解答，我也确实发现了这个问题，似乎是如果从macOS关机，直接开机启动macOS，就没有任何问题；如果关机后先启动Windows，再启动macOS就会出现问题1，但是重启macOS后可解决问题。我了解到好像是Monterey的问题，Monterey会锁BIOS，但是外接键盘可以使用，我试了试Big Sur，就不会出现上述问题2。

**Comment by diyanqi** [comment]
嗯，这可能是最佳的解决方式了。如果要修复上述问题，可能要到系统层面去更改，那就超出我的能力范围了🤣
